    var homeoBrandData = [
        // SBL
        {
        title: "SBL Nux Vomica 30 CH (30ml)",
        src: "https://static.oxinis.com/healthmug/image/product/1365-1-400.jpg",
        tagLine: "Anger, Irritation, Constipation, Nausea Vomiting, Colic, Joint pains",
        price: 90,
        offprice: 70,
        discount: 14,
        },
        {
            title: "SBL Thuja Occidentalis 200 CH (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/1883-1-400.jpg",
            tagLine: "Warts, overgrowth of tissues, Stiff Joints, Brown spots on skin.",
            price: 100,
            offprice: 95,
            discount: 5,
        },
        {
            title: "SBL Calcarea Fluoricum 6X (25g)",
            src: "https://static.oxinis.com/healthmug/image/product/873-1-400.jpg",
            tagLine: "For Varicose Veins, Piles, blur vision, Tooth cavity, Gouty swellings",
            price: 95,
            offprice: 90,
            discount: 5,
        },
        {
            title: "SBL Kali Phosphorica 6X (25g)",
            src: "https://static.oxinis.com/healthmug/image/product/878-1-400.jpg",
            tagLine: "For Fear, Bad breath, Bed wetting, Constipation, Late menses, Energy",
            price: 95,
            offprice: 90,
            discount: 5,
        },
        {
            title: "SBL Clearstone Drops (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/524-4-400.jpg",
            tagLine: "https://static.oxinis.com/healthmug/image/product/524-4-400.jpg",
            price: 125,
            offprice: 119,
            discount: 5,
        },

        //   Willmar Schwabe
        {
            title: "Willmar Schwabe India Berberis Aquifolium 1X (Q) (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/6308-1-200.jpg",
            tagLine: "",
            price: 195,
            offprice: "",
            discount: "",
        },

        {
            title: "Willmar Schwabe India Ashwagandha (Withania somnifera) 1X (Q) (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/6300-1-400.jpg",
            tagLine: "Joint Pains, Boosts Immunity, Weak Memory, Improves concentration",
            price: 100,
            offprice: "",
            discount: "",
        },

        {
            title: "Willmar Schwabe India Cydonia Vulgaris 30 CH (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/5633-1-400.jpg",
            tagLine: "Erectile dysfunction, premature ejaculation, Prostate complaints",
            price: 90,
            offprice: "",
            discount: "",
        },
        {
            title: "Willmar Schwabe India Syzygium Jambolanum 1X (Q) (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/6402-1-400.jpg",
            tagLine: "For Increased Amount of Sugar in the Blood, Urine and Related Symptoms",
            price: 100,
            offprice: "",
            discount: "",
        },
        {
            title: "Willmar Schwabe India Crataegus oxyacantha 1X (Q) (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/6330-1-400.jpg",
            tagLine: "Helps Tone Heart Muscles, Fatigue, Dyspnoea On Exertion, Angina",
            price: 100,
            offprice: 95,
            discount: 5,
        },
    // Dr. Reckweg

        {
            title: "Dr. Reckeweg R89 (Lipocol) (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/411-2-400.jpg",
            tagLine: "Helps to control Hair Loss, Graying of hair, thin hair, alopecia",
            price: 285,
            offprice: "",
            discount: "",
        },

        {
            title: "Dr. Reckeweg Calcarea Fluoricum 6X (20g)",
            src: "https://static.oxinis.com/healthmug/image/product/227-1-400.jpg",
            tagLine: "For Varicose Veins, Piles, blur vision, Tooth cavity, Gouty swellings",
            price: 170,
            offprice: "",
            discount: "",
        },

        {
            title: "Dr. Reckeweg R5 (Gastreu) (22ml)",
            src: "https://static.oxinis.com/healthmug/image/product/329-1-400.jpg",
            tagLine: "Relieves Burning pain in stomach, vomiting, acidity, gas trouble",
            price: 250,
            offprice: "",
            discount: "",
        },
        {
            title: "Dr. Reckeweg Aalserum 7X (20ml)",
            src: "https://static.oxinis.com/healthmug/image/product/1-1-400.jpg",
            tagLine: "Nephrotic syndrome,Difficult urination, High Creatinine, Albuminuria",
            price: 235,
            offprice: "",
            discount: "",
        },
        {
            title: "Dr. Reckeweg R42 (Haemovenin) (22ml)",
            src: "https://static.oxinis.com/healthmug/image/product/367-1-400.jpg",
            tagLine: "Useful in Varicose Veins, Eczema, Itching of legs and heaviness",
            price: 250,
            offprice: "",
            discount: "",
        },
        
    // B.Jain

        {
            title: "B Jain Syzygium Jambolanum 1X (Q) (100ml)",
            src: "https://static.oxinis.com/healthmug/image/product/66586-1-200.jpg",
            tagLine: "For Increased Amount of Sugar in the Blood, Urine and Related Symptoms",
            price: 185,
            offprice: 166,
            discount: 10,
        },

        {
            title: "B Jain Withania Somnifera 1X (Q) (100ml)",
            src: "https://static.oxinis.com/healthmug/image/product/66612-1-400.jpg",
            tagLine: "Joint Pains, Boosts Immunity, Weak Memory, Improves concentration",
            price: 185,
            offprice: 166,
            discount: 10,
        },
        {
            title: "B Jain Abroma Augusta 1X (Q) (100ml)",
            src: "https://static.oxinis.com/healthmug/image/product/66344-1-400.jpg",
            tagLine: "Excess thirst, High level of sugar, enuresis, vertigo, giddiness",
            price: 185,
            offprice: 166,
            discount: 10,
        },
        {
            title: "B Jain Guatteria Gaumeri Drops (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/7627-1-400.jpg",
            tagLine: "Controls High Cholesterol and Associated Symptoms, Hypercholesterolemia",
            price: 330,
            offprice: 329,
            discount: 0,
        },
        {
            title: "B Jain Berberis Vulgaris 1X (Q) (100ml)",
            src: "https://static.oxinis.com/healthmug/image/product/66399-1-400.jpg",
            tagLine: "Renal calculi, Arthritic pains, lumbago, Urinary incontinence",
            price: 185,
            offprice: 166,
            discount: 10,
        },
    // Bakson Aller
        {
            title: "Bakson Aller Aid Tablets (75tab)",
            src: "https://static.oxinis.com/healthmug/image/product/3050-3-400.jpg",
            tagLine: "Used in Running Nose, Sneezing, Watery Eyes, Sinusitis, Nasal Allergy",
            price: 185,
            offprice: 175,
            discount: 5,
        },
        {
            title: "Bakson Aller Aid Plus (Twin Pack) (1Pack)",
            src: "https://static.oxinis.com/healthmug/image/product/43207-1-400.jpg",
            tagLine: "For sinusitis, congestion, headache, Sneezing, blocked nose, cheek pain",
            price: 360,
            offprice: "",
            discount: "",
        },
        {
            title: "Bakson Slim & Fit Gelatin Capsules (30caps)",
            src: "https://static.oxinis.com/healthmug/image/product/54950-1-400.jpg",
            tagLine: "Natural Formula with the goodness of Garcinia, caralluma and Green tea extract",
            price: 245,
            offprice: "",
            discount: "",
        },
        {
            title: "Bakson Rheum Aid Tablets (75tab)",
            src: "https://static.oxinis.com/healthmug/image/product/3018-1-400.jpg",
            tagLine: "Gout, Arthritis/Joint Pains, Slip Disc and Muscular Weakness/Fatigue",
            price: 200,
            offprice: 190,
            discount: 5,
        },
        {
            title: "Bakson Throat Aid Tablets (75tab)",
            src: "https://static.oxinis.com/healthmug/image/product/3030-1-400.jpg",
            tagLine: "Sore Throat, Hoarseness with Loss of Voice, Laryngitis and Pharyngitis",
            price: 185,
            offprice: 175,
            discount: 5,
        },
    // Lords  
        {
            title: "Lords Bio Combination No 20 (450g)",
            src: "https://static.oxinis.com/healthmug/image/product/42461-1-400.jpg",
            tagLine: "For Acne, Eczema, Psoriasis, Urticaria, Herpes, Scalp eruptions",
            price: 620,
            offprice: 557,
            discount: 5,
        },

        {
            title: "Lords Dige Tone Syrup (450ml)",
            src: "https://static.oxinis.com/healthmug/image/product/41979-1-400.jpg",
            tagLine: "Relieves Indigestion, Acidity, Gastritis, Flatulence, Constipation",
            price: 320,
            offprice: 287,
            discount: 5,
        },
        {
            title: "Lords Carbo Veg 30 CH (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/126541-1-400.jpg",
            tagLine: "Bleeding Gums, Flatulence, Indigestion, Colic, Hemorrhoids Painful, Overeating",
            price: 85,
            offprice: 76,
            discount: 11,
        },
        {
            title: "Lords Ylo Tablets (50tab)",
            src: "https://static.oxinis.com/healthmug/image/product/7432-2-400.jpg",
            tagLine: "Relieves Constipation, Hard Stools, Regulates Bowel Movement, Anal Itching",
            price: 135,
            offprice: 121,
            discount: 10,
        },
        {
            title: "Lords Glow Care Drops (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/41993-1-400.jpg",
            tagLine: "For Acne, Pimples, Removing Dark Rings Around Eyes, Fairness of Skin",
            price: 105,
            offprice: 84,
            discount: 20,
        },
    // New Life  
        {
            title: "New Life Bach Flower Rescue Remedy (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/2654-1-400.jpg",
            tagLine: "Bach Flower Rescue Remedy",
            price: 100,
            offprice: "",
            discount: "",
        },
        {
            title: "New Life Bach Flower Rescue Remedy (100ml)",
            src: "https://static.oxinis.com/healthmug/image/product/131245-1-400.jpg",
            tagLine: "Bach Flower Rescue Remedy",
            price: 200,
            offprice: 196,
            discount: 2,
        },
        {
            title: "New Life Bach Flower White Chestnut (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/2650-1-400.jpg",
            tagLine: "Repeated Unwanted Thoughts, Mental fatigue, Sleeplessness, Insomnia.",
            price: 100,
            offprice: 98,
            discount: 2,
        },
        {
            title: "New Life Bach Flower Star Of Bethlehem (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/2644-1-400.jpg",
            tagLine: "Helps in managing anxiety, difficult sleep and disheartedness after loss of loved ones",
            price: 100,
            offprice: 98,
            discount: 2,
        },
        {
            title: "New Life NL-12 (Low Blood Pressure Drops) (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/5505-1-400.jpg",
            tagLine: "",
            price: 140,
            offprice: "",
            discount: "",
        },
    
    //   Allen
        {
            title: "Allen Varicose Vein Drops (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/80315-1-400.jpg",
            tagLine: "For Varicose Veins, Heaviness, Swelling, Inflammation, blocked veins",
            price: 160,
            offprice: 152,
            discount: 5,
        },
        {
            title: "Allen Varicose Vein Massage Oil (60ml)",
            src: "https://static.oxinis.com/healthmug/image/product/80317-1-400.jpg",
            tagLine: "varicose, spider veins, broken capillaries, heavy legs",
            price: 120,
            offprice: 114,
            discount: 5,
        },
        {
            title: "Allen A84 Lipoma Drops (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/7603-1-400.jpg",
            tagLine: "For swollen lymph nodes, glandular swelling",
            price: 160,
            offprice: 152,
            discount: 5,
        },
        {
            title: "Allen A70 Irritable Bowel Syndrome (IBS) Drops (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/7589-1-400.jpg",
            tagLine: "Helps in Loose motions, Diarhhoea, Colic pain, Nausea, dehydration",
            price: 160,
            offprice: 153,
            discount: 4,
        },
        {
            title: "Allen Varicose Vein Massage Oil (100ml)",
            src: "Allen Varicose Vein Massage Oil (100ml)",
            tagLine: "varicose, spider veins, broken capillaries, heavy legs",
            price: 170,
            offprice: "",
            discount: "",
        },
    // Wheezal  

        {
            title: "Wheezal WL-28 Piles Drops (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/7397-2-200.jpg",
            tagLine: "Relieves Painful, Bleeding, Burning Piles, Anal Fissure, Itching at anus",
            price: 160,
            offprice: 152,
            discount: 5,
        },
    
        {
            title: "Wheezal WL-53 Hydrocele Drops (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/12196-1-400.jpg",
            tagLine: "Relieves Hardness, Swelling of Scrotum, Testes, male private part pain",
            price: 160,
            offprice: 152,
            discount: 5,
     },
  
        {
            title: "Wheezal Sarsa Syrup (450ml)",
            src: "https://static.oxinis.com/healthmug/image/product/5604-2-400.jpg",
            tagLine: "For Pimples, Acne, Psoriasis, Itching, Effective Blood Purifier",
            price: 320,
            offprice: 303,
            discount: 5,
        },
        
        {
            title: "Wheezal WL-7 Cold And Cough Drops (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/7376-2-400.jpg",
            tagLine: "Relieves Cold, Cough, Watery Nose, Sneezing, Itchy Eyes, Blocked nose",
            price: 145,
            offprice: 136,
            discount: 6,
        },
        
        {
            title: "Wheezal Gastrolex Drops (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/5615-1-400.jpg",
            tagLine: "For Flatulence, Dyspepsia, Gastritis, Indigestion, Bloated and Pain in Stomach",
            price: 125,
            offprice: 120,
            discount: 4,
        },
// Haslab
        {
            title: "Haslab Laxyalo Tablet (10tab)",
            src: "https://static.oxinis.com/healthmug/image/product/5587-2-400.jpg",
            tagLine: "Laxative, Easy Passage of Stool, Relieves Constipation, Indigestion",
            price: 40,
            offprice: "",
            discount: "",
        },
        
        {
            title: "Haslab Alfalfa Super Tonic with Vitamin ABCD (450ml)",
            src: "https://static.oxinis.com/healthmug/image/product/5576-3-400.jpg",
            tagLine: "Tonic for Anaemia, Loss of Appetite, Flatulence, Weakness, Illness",
            price: 255,
            offprice: 242,
            discount: 5,
        },
        
        {
            title: "Haslab G H Phos Tonic with Vitamin B and Iron (450ml)",
            src: "https://static.oxinis.com/healthmug/image/product/5574-2-400.jpg",
            tagLine: "Tonic for Nervous Exhaustion, Depression, Loss of Memory, Brain Fag",
            price: 270,
            offprice: "",
            discount: "",
        },
        
        {
            title: "Haslab Mullein Ear Drops (10ml)",
            src: "https://static.oxinis.com/healthmug/image/product/70629-1-400.jpg",
            tagLine: "Homoeopathic medicine for ear, helpful in ear ache, watery ear, loss of hearing ability",
            price: 50,
            offprice: 47,
            discount: 6,
        },
        
        {
            title: "Haslab DROX 10 (Filarin Drops - Filaria) (30ml)",
            src: "https://static.oxinis.com/healthmug/image/product/7230-1-400.jpg",
            tagLine: "For Inflammation of Veins in Lower Limbs with Swelling, Enlarged Testes",
            price: 150,
            offprice: "",
            discount: "",
        },
    ]

