var nutritionData = [
  {
    title: "Baidyanath Ayurved Ashwagandha Tablets (60tab)",
    src: "https://static.oxinis.com/healthmug/image/product/152938-1-200.jpg ",
    tagLine:
      "General Wellness Tablets act as an immunity booster and helps to handle stress and anxiety",
    price: 150,
    offprice: 145,
    discount: 3,
  },
  {
    title: "Kaahan Ayurvedas Sehat King Powder (160g)",
    src: "https://static.oxinis.com/healthmug/image/product/65818-1-200.jpg ",
    tagLine: "",
    price: 840,
    offprice: 749,
    discount: 11,
  },

  {
    title: "Bigmuscles Nutrition Premium Gold Whey Protein ",
    src: "https://static.oxinis.com/healthmug/image/product/137209-1-200.jpg ",
    tagLine:
      "100% protein from whey isolate and whey concentrate, promotes muscle growth",
    price: 2299,
    offprice: 1299,
    discount: 43,
  },
  {
    title: "FDC Ltd Electral Powder Unflavoured (21.8g)",
    src: "https://static.oxinis.com/healthmug/image/product/135348-1-200.jpg ",
    tagLine: "",
    price: 20,
    offprice: "",
    discount: "",
  },
  {
    title: "Bakson Vitamin D Plus Tablets (30tab)",
    src: "https://static.oxinis.com/healthmug/image/product/54952-1-200.jpg ",
    tagLine:
      " Multivitamin and Multi mineral supplement for healthy functioning of body, meant for all age groups",
    price: 160,
    offprice: "",
    discount: "",
  },
  {
    title: "Axiom Sheesham Juice (500ml)",
    src: "https://static.oxinis.com/healthmug/image/product/56372-1-200.jpg ",
    tagLine:
      "It is an Ayurvedic juice which heals non-healing wounds, ulcers and is effective in acidity",
    price: 180,
    offprice: "",
    discount: "",
  },
  {
    title: "Indusviva Ipulse Immune Boosting And Antioxidan",
    src: "https://static.oxinis.com/healthmug/image/product/152650-1-200.jpg ",
    tagLine: "",
    price: 3597,
    offprice: "",
    discount: "",
  },
  {
    title: "Axiom Karela Jamun Swaras (1000ml)",
    src: "https://static.oxinis.com/healthmug/image/product/56346-1-200.jpg ",
    tagLine: "100% Natural Karela Jamun juice for overall wellbeing",
    price: 300,
    offprice: "",
    discount: "",
  },
  {
    title: "Sri Sri Tattva Karela - Jamun Juice (1000ml)",
    src: "https://static.oxinis.com/healthmug/image/product/53677-1-200.jpg ",
    tagLine:
      "Helps to lower increased blood sugar level, purifies blood, and improves digestive system",
    price: 280,
    offprice: 239,
    discount: 15,
  },

  {
    title: "Himalayan Organics Milk Thistle Extract Silymar",
    src: "https://static.oxinis.com/healthmug/image/product/137937-1-200.jpg ",
    tagLine: "",
    price: 1999,
    offprice: 699,
    discount: 65,
  },
  {
    title: "Jiva Ayurveda Amla Chatpata Candy (450g)",
    src: "https://static.oxinis.com/healthmug/image/product/65520-2-200.jpg ",
    tagLine:
      "Amla chatpata candy, ayurvedic herb mix candy, improves digestion,strengthen immune system.",
    price: 220,
    offprice: "",
    discount: "",
  },
  {
    title: "Dr. Lal El Mecobin (30tab)",
    src: "https://static.oxinis.com/healthmug/image/product/11521-2-200.jpg ",
    tagLine:
      "El Mecobin Active Form of Vitamin B12. Promotes Healthy Neurological Activity",
    price: 400,
    offprice: "",
    discount: "",
  },
  {
    title: "Basic Ayurveda Brahmi Juice (500ml)",
    src: "https://static.oxinis.com/healthmug/image/product/2429-2-200.jpg ",
    tagLine:
      "Basic Ayurveda Brahmi Juice is an ideal juice which Improves Memory,Sharpens Thinking, Provides Good Menta",
    price: 240,
    offprice: 239,
    discount: 0,
  },
  {
    title: "Dabur Hajmola Maha Candy Albela Aam And Chulbul",
    src: "https://static.oxinis.com/healthmug/image/product/128832-1-200.jpg ",
    tagLine:
      "Helps in improving digestion and managing common stomach ailments",
    price: 100,
    offprice: "",
    discount: "",
  },
  {
    title: "Swadeshi Ayurved Amla Sweet (900g)",
    src: "https://static.oxinis.com/healthmug/image/product/151714-1-200.jpg ",
    tagLine:
      "Rich in Vitamin E and antioxidants ,aids in digestion, Increase red blood cells, eyesight improvement, Immu",
    price: 400,
    offprice: 380,
    discount: 5,
  },
  {
    title: "Bigmuscles Nutrition Freak A Next Level Pre-Workout",
    src: "https://static.oxinis.com/healthmug/image/product/137219-1-200.jpg ",
    tagLine:
      "Powerful pre-workout, helps you improve mental focus and go hard at the gym",
    price: 1199,
    offprice: 1079,
    discount: 10,
  },
  {
    title: "GAT Sport Testrol Gold ES Tablet (60tab)",
    src: "https://static.oxinis.com/healthmug/image/product/108205-1-200.jpg ",
    tagLine: "Endures perfromance, strength and boosts testosterone",
    price: 2499,
    offprice: 2299,
    discount: 8,
  },

  {
    title: "Dr Morepen Testosterone Booster Tablets (60tab)",
    src: "https://static.oxinis.com/healthmug/image/product/152340-1-200.jpg ",
    tagLine: "Maintain your stamina level, leaner body and stronger muscles.",
    price: 995,
    offprice: 696,
    discount: 30,
  },
  {
    title: "Sri Sri Tattva Organic Virgin Coconut Oil (200mg)",
    src: "https://static.oxinis.com/healthmug/image/product/53681-5-200.jpg ",
    tagLine: "Oil that can help keep your body healthy and efficient.",
    price: 300,
    offprice: 270,
    discount: 10,
  },
  {
    title: "Jiva Ayurveda Honey (500g)",
    src: "https://static.oxinis.com/healthmug/image/product/18987-2-200.jpg ",
    tagLine:
      "Boosts Immunity, Strengthens Respiratory System, Anti-Oxidant Properties",
    price: 190,
    offprice: "",
    discount: "",
  },
  {
    title: "Axiom Triphla Aloevera Juice (1000ml)",
    src: "https://static.oxinis.com/healthmug/image/product/56382-1-200.jpg ",
    tagLine:
      "Axiom Triphla Aloevera Juice With goodness of Aloevera, this herbal juice is effective in blood pressure",
    price: 275,
    offprice: 248,
    discount: 10,
  },
  {
    title: "Telephone Sat Isabgol (100g)",
    src: "https://static.oxinis.com/healthmug/image/product/7823-1-200.jpg ",
    tagLine: " Natural Product from Isabgol Seeds for constipation, digestion",
    price: 110,
    offprice: "",
    discount: "",
  },
  {
    title: "Healthvit Vitamin B12 1500Mcg (60tab)",
    src: "https://static.oxinis.com/healthmug/image/product/139152-1-200.jpg ",
    tagLine: "",
    price: 230,
    offprice: 225,
    discount: 2,
  },
  {
    title: "Axiom Chhoti Duddhi Juice (500ml)",
    src: "https://static.oxinis.com/healthmug/image/product/56328-1-200.jpg ",
    tagLine:
      "Useful to manage the blood sugar level,loose motion,stomach ulcer, nausea &amp; vomiting",
    price: 300,
    offprice: 299,
    discount: 0,
  },
  {
    title: "Tablets India Laktrum Powder (50g)",
    src: "https://static.oxinis.com/healthmug/image/product/121461-1-200.jpg ",
    tagLine: "",
    price: 449,
    offprice: "",
    discount: "",
  },
  {
    title: "Neuherbs Milk Thistle Liver Detox Capsules",
    src: "https://static.oxinis.com/healthmug/image/product/149642-1-200.jpg ",
    tagLine:
      " Quality Milk thistle capsules that aids in liver detox &amp; Kidney Health improvement",
    price: 995,
    offprice: 639,
    discount: 36,
  },
  {
    title: "BPH Saptamrita Ras (500ml)",
    src: "https://static.oxinis.com/healthmug/image/product/154036-1-200.jpg ",
    tagLine: "",
    price: 210,
    offprice: 200,
    discount: 5,
  },
  {
    title: "Natrol Biotin 10,000 mcg (100tab)",
    src: "https://static.oxinis.com/healthmug/image/product/59975-1-200.jpg ",
    tagLine: "Biotin supplement that helps to maintain healthy hair and skin",
    price: 1499,
    offprice: 1299,
    discount: 13,
  },
  {
    title: "Baidyanath Ayurvedant Amla Juice (200ml)",
    src: "https://static.oxinis.com/healthmug/image/product/47384-4-200.jpg ",
    tagLine:
      " Ayurvedant Amla Juice is an ayurvedic juice which protects against Infections, Nourishes &amp; Rejuvenates",
    price: 30,
    offprice: 29,
    discount: 3,
  },
  {
    title: "Herbal Canada Noni Juice (500ml)",
    src: "https://static.oxinis.com/healthmug/image/product/166112-1-200.jpg ",
    tagLine: "",
    price: 350,
    offprice: 310,
    discount: 11,
  },
  {
    title: "Apollo Noni Juice Concentrate Classic (450ml)",
    src: "https://static.oxinis.com/healthmug/image/product/67159-4-200.jpg ",
    tagLine: "",
    price: 750,
    offprice: 739,
    discount: 1,
  },
  {
    title: "Dr. Lal El D3 Sachets (20Sachet)",
    src: "https://static.oxinis.com/healthmug/image/product/11513-1-200.jpg ",
    tagLine: "Ensure strong bones and a strong immune system",
    price: 410,
    offprice: "",
    discount: "",
  },
  {
    title: "Axiom Karela Jamun Swaras (500ml)",
    src: "https://static.oxinis.com/healthmug/image/product/56345-1-200.jpg ",
    tagLine: "100% Natural Karela Jamun juice for overall wellbeing",
    price: 160,
    offprice: 144,
    discount: 10,
  },
  {
    title: "Himalayan Organics Biotin 10000Mcg Tablets ",
    src: "https://static.oxinis.com/healthmug/image/product/138000-1-200.jpg ",
    tagLine:
      "It facilitates healthier hair growth, glowing skin, and stronger nails",
    price: 1295,
    offprice: 599,
    discount: 54,
  },
  {
    title: "Neuherbs Inch Burn Advanced Formula Capsules ",
    src: "https://static.oxinis.com/healthmug/image/product/149643-1-200.jpg ",
    tagLine:
      "Fuel up your workout helps boost energy levels and physical performance.",
    price: 999,
    offprice: 399,
    discount: 60,
  },
  {
    title: "Alvizia Alenflax Flaxseed Oil 1000 Mg Capsules ",
    src: "https://static.oxinis.com/healthmug/image/product/65794-1-200.jpg ",
    tagLine:
      "Organic flax seed oil cold pressed veg capsules, rich in omega 3, 6 &amp; 9 fatty acids with EPA+ DHA",
    price: 800,
    offprice: 340,
    discount: 57,
  },
  {
    title: "Dr Morepen Natural &amp; Pure Honey Nmr Tested ",
    src: "https://static.oxinis.com/healthmug/image/product/149246-1-200.jpg ",
    tagLine:
      "It has anti-oxidants and anti-bacterial properties that help build immunity",
    price: 198,
    offprice: 158,
    discount: 20,
  },
  {
    title: "Bakson Nail and Hair Aid Tablets (30tab)",
    src: "https://static.oxinis.com/healthmug/image/product/53208-1-200.jpg ",
    tagLine:
      "Provides Collagen and Keratin that helps to improve Texture and Strength to Hair and Nails",
    price: 175,
    offprice: 170,
    discount: 3,
  },
  {
    title: "Swadeshi Ayurved Amla Murabba (1000g)",
    src: "https://static.oxinis.com/healthmug/image/product/130963-1-200.jpg ",
    tagLine: "Ayurvedic eatable for digestive benifits",
    price: 210,
    offprice: 189,
    discount: 10,
  },
  {
    title: "Baidyanath Chyawan-Fit Suger Free Chawanprash",
    src: "https://static.oxinis.com/healthmug/image/product/44239-5-200.jpg ",
    tagLine:
      "Sugar-free immunity builder to keep you going with your daily chores",
    price: 395,
    offprice: 375,
    discount: 5,
  },
];
